language: node_js
notifications:
  email: false
  slack: conveyal:WQxmWiu8PdmujwLw4ziW72Gc
node_js:
  - '12' # must be at least v10 for mastarm 5
cache:
  yarn: true
before_install:
  - npm i -g codecov
  # Use updated python to avoid SSL insecure warnings:
  # https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  - python --version
  - pyenv versions
  - pyenv global 2.7.14
  - pip install --user mkdocs
script:
  - yarn run lint
  - yarn run lint-messages
  - yarn run flow
  - yarn run cover-client
  - codecov
  - yarn run build --minify
  - mkdocs build

# If sudo is disabled, CI runs on container based infrastructure (allows caching &c.)
sudo: false

# Push results to codecov.io
after_success:
  - bash <(curl -s https://codecov.io/bash)
  # only deploy the release to github as the package is not needed on npm
  - semantic-release --prepare false --publish @semantic-release/github --verify-conditions @semantic-release/github
