language: node_js
notifications:
  email: false
  slack: conveyal:WQxmWiu8PdmujwLw4ziW72Gc
node_js:
  - '8'
services:
  # needed for e2e tests to start datatools-server
  - mongodb
  - postgresql
addons:
  postgresql: 9.6
cache:
  directories:
    - $HOME/.cache/yarn
    - $HOME/.cache/pip
before_install:
  # Use updated python to avoid SSL insecure warnings:
  # https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  - python --version
  - pyenv versions
  - pyenv global 2.7.14
  - pip install --user mkdocs
  # create database for e2e tests
  - psql -U postgres -c 'CREATE DATABASE catalogue;'
  # add aws credentials for datatools-server
  - mkdir ~/.aws && printf '%s\n' '[default]' 'aws_access_key_id=${AWS_ACCESS_KEY_ID}' 'aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}' 'region=us-east-1' > ~/.aws/config
script:
  - yarn run lint
  - yarn run lint-messages
  - yarn run flow
  - yarn run cover-client
  # upload coverage results from unit tests and then delete coverage reports
  - bash <(curl -s https://codecov.io/bash) -c -F unit_tests
  - yarn run cover-end-to-end
  # upload coverage results from e2e tests and then delete coverage reports
  - bash <(curl -s https://codecov.io/bash) -c -F end_to_end_tests
  - yarn run build -- --minify
  - mkdocs build

# If sudo is disabled, CI runs on container based infrastructure (allows caching &c.)
sudo: false

# Push results to codecov.io
after_success:
  - yarn run semantic-release
