site_name: Transit Data Tools Docs
site_url: http://mtc-datatools.readthedocs.io
repo_url: https://github.com/conveyal/datatools-manager
docs_dir: docs
site_dir: target/mkdocs
theme: readthedocs
extra_css: [style.css]

pages:
- Home: 'index.md'
- User Guide:
  - Data Manager:
    - 'Introduction': 'user/introduction.md'
    - 'Managing Projects & Feeds': 'user/managing-projects-feeds.md'
    - 'Publishing Feeds': 'user/publishing-feeds.md'
    - Feed Version Summary: 'user/feed-version-summary.md'
    - 'Managing Users': 'user/managing-users.md'
    - 'Service Alerts Manager': 'user/service-alerts.md'
    - 'eTID Configuration Manager': 'user/sign-config.md'
    - 'Searching for Routes and Stops': 'user/searching-routes-stops.md'
    - 'GTFS+ Editor': 'user/gtfs-plus-editor.md'
    - 'Appendix: GTFS Validation Warnings': 'user/appendix-gtfs-warnings.md'
  - 'GTFS Editor':
    - Introduction: 'user/editor/introduction.md'
    - Routes: 'user/editor/routes.md'
    - Patterns: 'user/editor/patterns.md'
    - Stops: 'user/editor/stops.md'
    - 'Schedules/Timetables': 'user/editor/schedules.md'
    - Calendars: 'user/editor/calendars.md'
    - Fares: 'user/editor/fares.md'
- Development Guide:
    - Deployment: dev/deployment.md
    - Development: dev/development.md
    - API Interaction: dev/api_interaction.md
    - Migration: dev/migration.md
