name: PR E2E Checks

on: [pull_request]

jobs:
  pull-request-e2e-check:
    if: "${{
      github.base_ref == 'master' ||
      (github.base_ref == 'dev' && github.event.pull_request.reviewDecision == 'approved') ||
      (github.base_ref == 'dev' && startsWith(github.ref_name, 'dependabot/'))
      }}"
    uses: ./.github/workflows/node-ci.yml
    with:
      # Run e2e tests on commits to:
      # - PRs to master
      # - Approved PRs to dev
      # - PRs to dev on branches created by dependabot
      e2e: true
      failIfNotE2e: true
