name: PR E2E Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, review_requested]
  pull_request_review:
    types: [submitted]
jobs:
  pr-e2e-check:
    # Run e2e tests
    # on pull request approval
    # on pull request review request
    # on commits to:
    # - PRs to master
    # - Approved PRs to dev
    # - PRs to dev on branches created by dependabot
    if: "${{
      github.event_name == 'pull_request_review' && github.event.review.state == 'approved' ||
      github.event_name == 'pull_request' && (
        github.event.action == 'review_requested' ||
        github.base_ref == 'master' ||
        (github.base_ref == 'dev' && (
          github.event.pull_request.reviewDecision == 'approved' ||
          startsWith(github.ref_name, 'dependabot/')
        ))
      )
      }}"
    uses: ./.github/workflows/node-ci.yml
    with:
      e2e: true
    secrets: inherit
